apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: tap-test
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
  name: tap-test
spec:
  build:
    env:
    - name: BP_DOTNET_PROJECT_PATH
      value: ./TAP-Test
    - name: BP_DOTNET_FRAMEWORK_VERSION
      value: 8.0.0
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/language: dotnet
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/version: "8.0"
  source:
    git:
      ref:
        branch: master
      url: https://github.com/CaswellT/TAP-Test.git